services:
  backend:
    build:
      context: backend
      target: development
    secrets:
      - db-password
    depends_on:
      - db
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  db:
    image: mariadb
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  proxy:
    build: proxy
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
